apiVersion: apps/v1

kind: Deployment

metadata:

  name: wisecow-deployment

spec:

  replicas: 1 # Adjust the number of replicas as needed

  selector:

    matchLabels:

      app: wisecow

  template:

    metadata:

      labels:

        app: wisecow

    spec:

      containers:

      - name: wisecow-container

        image: demoACR1.azurecr.io/wisecow:latest # Replace <acr-name> with your ACR name

        ports:

        - containerPort: 4499 # Specify the port your application listens on
 
 
---

apiVersion: v1

kind: Service

metadata:

  name: wisecow-service

spec:

  selector:

    app: wisecow

  ports:

  - protocol: TCP

    port: 80 # The port on which the service will be exposed

    targetPort: 4499 # The port your application listens on

  type: LoadBalancer # Use 'LoadBalancer' if you want to expose the service externally
